--- #YAML:1.0
name: ExtUtils-CBuilder
version: 0.09_01
author:
  - Ken Williams, kwilliams@cpan.org
abstract: Compile and link C code for Perl modules
license: perl
requires:
  File::Basename: 0
  File::Spec: 0
  Text::ParseWords: 0
build_requires:
  Test: 0
provides:
  ExtUtils::CBuilder:
    file: lib/ExtUtils/CBuilder.pm
    version: 0.09_01
  ExtUtils::CBuilder::Base:
    file: lib/ExtUtils/CBuilder/Base.pm
    version: 0.00_01
  ExtUtils::CBuilder::Platform::Unix:
    file: lib/ExtUtils/CBuilder/Platform/Unix.pm
  ExtUtils::CBuilder::Platform::VMS:
    file: lib/ExtUtils/CBuilder/Platform/VMS.pm
  ExtUtils::CBuilder::Platform::Windows:
    file: lib/ExtUtils/CBuilder/Platform/Windows.pm
  ExtUtils::CBuilder::Platform::Windows::BCC:
    file: lib/ExtUtils/CBuilder/Platform/Windows.pm
  ExtUtils::CBuilder::Platform::Windows::GCC:
    file: lib/ExtUtils/CBuilder/Platform/Windows.pm
  ExtUtils::CBuilder::Platform::Windows::MSVC:
    file: lib/ExtUtils/CBuilder/Platform/Windows.pm
  ExtUtils::CBuilder::Platform::aix:
    file: lib/ExtUtils/CBuilder/Platform/aix.pm
  ExtUtils::CBuilder::Platform::cygwin:
    file: lib/ExtUtils/CBuilder/Platform/cygwin.pm
  ExtUtils::CBuilder::Platform::darwin:
    file: lib/ExtUtils/CBuilder/Platform/darwin.pm
  ExtUtils::CBuilder::Platform::os2:
    file: lib/ExtUtils/CBuilder/Platform/os2.pm
generated_by: Module::Build version 0.26
